import React, { useState, useEffect } from "react";
import { Key, Clock, Copy, Check, ShieldCheck, Sparkles, AlertCircle, RefreshCw } from "lucide-react";
import { useAuthContext } from "../context/AuthContext";
import { getAdminInviteCodes, generateAdminInviteCode, AdminInviteCode } from "../services/adminInviteService";
import { CustomToast, ToastConfig } from "../components/CustomToast";
import "../styles/AdminInvites.css";

export default function AdminInvites() {
  const { user } = useAuthContext();
  const [codes, setCodes] = useState<AdminInviteCode[]>([]);
  const [copiedCode, setCopiedCode] = useState<string | null>(null);
  const [toast, setToast] = useState<ToastConfig | null>(null);
  const [now, setNow] = useState<number>(Date.now());

  const refreshCodes = () => {
    setCodes(getAdminInviteCodes());
  };

  useEffect(() => {
    refreshCodes();
    const timer = setInterval(() => {
      setNow(Date.now());
      refreshCodes();
    }, 1000);
    return () => clearInterval(timer);
  }, []);

  const handleGenerate = () => {
    const newCode = generateAdminInviteCode(user?.email || "admin@amu.gov");
    refreshCodes();
    setToast({
      type: "success",
      title: "12-Digit Code Generated",
      message: `Admin Invite Code ${newCode.code} generated! Valid for 5 minutes.`
    });
  };

  const handleCopy = (code: string) => {
    let success = false;
    if (navigator.clipboard && window.isSecureContext) {
      navigator.clipboard.writeText(code).then(() => {
        setCopiedCode(code);
      }).catch(() => {
        fallbackCopy(code);
      });
      success = true;
    } else {
      success = fallbackCopy(code);
    }

    if (success || true) {
      setCopiedCode(code);
      setToast({
        type: "info",
        title: "Code Copied to Clipboard",
        message: `Code ${code} copied! Share with recipient to claim within 5 minutes.`
      });
      setTimeout(() => setCopiedCode(null), 3000);
    }
  };

  const fallbackCopy = (text: string) => {
    const textArea = document.createElement("textarea");
    textArea.value = text;
    textArea.style.position = "fixed";
    textArea.style.left = "-999999px";
    textArea.style.top = "-999999px";
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();
    let res = false;
    try {
      res = document.execCommand("copy");
    } catch (err) {
      console.error("Fallback copy failed", err);
    }
    document.body.removeChild(textArea);
    return res;
  };

  const formatTimeLeft = (expiresAt: number) => {
    const diff = Math.max(0, Math.floor((expiresAt - now) / 1000));
    if (diff === 0) return "Expired";
    const mins = Math.floor(diff / 60);
    const secs = diff % 60;
    return `${mins.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")} remaining`;
  };

  return (
    <div className="admin-invites-page">
      {/* Page Header */}
      <div className="page-header">
        <div className="header-left-title">
          <div className="title-icon-badge neu-btn">
            <Key size={26} color="#15803d" />
          </div>
          <div>
            <h1 className="page-title">Admin Invites Management</h1>
            <p className="page-subtitle">Generate 12-digit single-use invite codes to grant Authority Admin privileges</p>
          </div>
        </div>

        <button className="btn-primary-neu flex items-center gap-2" onClick={handleGenerate}>
          <Sparkles size={18} />
          <span>Generate 12-Digit Invite Code</span>
        </button>
      </div>

      {/* Hero Banner */}
      <div className="invite-hero-banner neu-card">
        <div className="hero-content">
          <div className="badge-pill">
            <Clock size={14} color="#f59e0b" />
            <span>5-MINUTE EXPIRATION SECURITY POLICY</span>
          </div>
          <h2>Generate Role Upgrade Invite Codes</h2>
          <p>
            Upgrading an account role to <strong>District Authority Admin</strong> requires a 12-digit invite code. Codes generated below are valid for <strong>5 minutes</strong> and expire automatically if unclaimed.
          </p>
        </div>
      </div>

      {/* Active & Historical Codes Table */}
      <div className="table-card neu-card">
        <div className="table-header">
          <h3>Generated Invite Codes Registry</h3>
          <button className="neu-btn refresh-btn" onClick={refreshCodes}>
            <RefreshCw size={14} /> Refresh List
          </button>
        </div>

        <table className="table">
          <thead>
            <tr>
              <th>12-Digit Code</th>
              <th>Generated By</th>
              <th>Created At</th>
              <th>Time Left / Status</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {codes.length === 0 ? (
              <tr>
                <td colSpan={5} className="empty-cell">
                  No invite codes generated yet. Click <strong>Generate 12-Digit Invite Code</strong> above.
                </td>
              </tr>
            ) : (
              codes.map((item, idx) => {
                const isExpired = now > item.expiresAt || item.status === "expired";
                const isClaimed = item.status === "claimed";
                const isActive = !isExpired && !isClaimed;

                return (
                  <tr key={idx}>
                    <td>
                      <span className="invite-code-display">{item.code}</span>
                    </td>
                    <td>
                      <span className="generated-by">{item.generatedBy}</span>
                    </td>
                    <td>
                      <span className="created-time">
                        {new Date(item.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })}
                      </span>
                    </td>
                    <td>
                      {isClaimed ? (
                        <span className="badge status-verified">
                          <Check size={12} /> Claimed ({item.claimedBy})
                        </span>
                      ) : isExpired ? (
                        <span className="badge status-rejected">
                          <AlertCircle size={12} /> Expired
                        </span>
                      ) : (
                        <span className="badge status-pending">
                          <Clock size={12} /> {formatTimeLeft(item.expiresAt)}
                        </span>
                      )}
                    </td>
                    <td>
                      {isActive && (
                        <button
                          className="action-btn neu-btn copy-btn"
                          onClick={() => handleCopy(item.code)}
                          title="Copy Code"
                        >
                          {copiedCode === item.code ? <Check size={14} color="#10b981" /> : <Copy size={14} />}
                          <span>{copiedCode === item.code ? "Copied" : "Copy Code"}</span>
                        </button>
                      )}
                    </td>
                  </tr>
                );
              })
            )}
          </tbody>
        </table>
      </div>

      {/* Mandatory Footer Branding */}
      <footer className="doc-tab-footer" style={{ marginTop: '2.5rem' }}>
        <p>Designed, Developed by Akash Mishra.</p>
      </footer>

      <CustomToast toast={toast} onClose={() => setToast(null)} />
    </div>
  );
}
